# Generated by Django 4.1.2 on 2022-11-13 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Part",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="Name")),
                (
                    "condition",
                    models.CharField(
                        choices=[("new", "New"), ("used", "Used")],
                        max_length=4,
                        verbose_name="Condition",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("oem", "OEM"), ("aftermarket", "Aftermarket")],
                        max_length=11,
                        verbose_name="Type",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Price (in CAD)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Part",
                "verbose_name_plural": "Parts",
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "manufacturer",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="manufacturer"
                    ),
                ),
                (
                    "model",
                    models.CharField(blank=True, max_length=255, verbose_name="model"),
                ),
                (
                    "color",
                    models.CharField(blank=True, max_length=255, verbose_name="color"),
                ),
                (
                    "vin",
                    models.CharField(
                        max_length=17,
                        primary_key=True,
                        serialize=False,
                        verbose_name="vin",
                    ),
                ),
            ],
            options={
                "verbose_name": "vehicle",
                "verbose_name_plural": "vehicles",
            },
        ),
    ]
