# Generated by Django 4.1.2 on 2022-11-07 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shop",
            name="availability",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="available hours"
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="num_bays",
            field=models.IntegerField(
                blank=True, default=1, null=True, verbose_name="number of service bays"
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="num_employees",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="number of employees"
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="shopHours",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="shop hours"
            ),
        ),
    ]
