# Generated by Django 4.1.2 on 2022-11-29 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0012_remove_appointment_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="duration",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="appointment duration in hours"
            ),
        ),
    ]
