# Generated by Django 4.1.2 on 2023-01-02 05:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0013_appointment_duration"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shops.shop"
                    ),
                ),
            ],
            options={
                "verbose_name": "Shop Availability",
                "verbose_name_plural": "Shop Availability",
            },
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="date",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="duration",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="time",
        ),
        migrations.AddField(
            model_name="appointment",
            name="end_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="appointment",
            name="start_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("completed", "Completed"),
                    ("no show", "No Show"),
                    ("in_progress", "In Progress"),
                    ("done", "Done"),
                    ("rework", "Rework"),
                    ("pending", "Pending"),
                ],
                default="pending",
                max_length=12,
                verbose_name="status",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="service",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shop_services",
                to="shops.shop",
            ),
        ),
        migrations.CreateModel(
            name="ShopAvailabilitySlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "shop_availability",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shops.shopavailability",
                    ),
                ),
            ],
            options={
                "verbose_name": "Availability Slot",
                "verbose_name_plural": "Availability Slots",
            },
        ),
        migrations.CreateModel(
            name="AppointmentSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("num_slots", models.PositiveIntegerField()),
                ("booked_slots", models.PositiveIntegerField(default=0)),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shops.appointment",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shops.shop"
                    ),
                ),
            ],
            options={
                "verbose_name": "Appointment Slot",
                "verbose_name_plural": "Appointment Slots",
            },
        ),
        migrations.AddConstraint(
            model_name="shopavailabilityslot",
            constraint=models.CheckConstraint(
                check=models.Q(("end_time__gt", models.F("start_time"))),
                name="ensure_start_is_before_end",
            ),
        ),
        migrations.AddConstraint(
            model_name="shopavailability",
            constraint=models.UniqueConstraint(
                fields=("shop", "date"), name="shop_date_unique_combination"
            ),
        ),
        migrations.AddConstraint(
            model_name="appointmentslot",
            constraint=models.CheckConstraint(
                check=models.Q(("end_time__gt", models.F("start_time"))),
                name="check_start_and_end_time",
            ),
        ),
    ]
