# Generated by Django 4.1.2 on 2023-01-02 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0015_remove_appointment_end_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointmentslot",
            name="appointment",
        ),
        migrations.AddField(
            model_name="appointmentslot",
            name="appointment",
            field=models.ManyToManyField(to="shops.appointment"),
        ),
    ]
