# Generated by Django 4.1.2 on 2023-01-02 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0016_remove_appointmentslot_appointment_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointmentslot",
            name="booked_slots",
        ),
        migrations.AddConstraint(
            model_name="appointmentslot",
            constraint=models.UniqueConstraint(
                fields=("shop", "start_time", "end_time"),
                name="unique_appointment_slot",
            ),
        ),
    ]
