# Generated by Django 4.1.2 on 2023-02-13 21:28

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0019_rename_appointment_appointmentslot_appointments_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="shop_email",
            field=models.EmailField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="shop's email address",
            ),
        ),
        migrations.AddField(
            model_name="shop",
            name="shop_phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region=None
            ),
        ),
    ]
