# Generated by Django 4.1.2 on 2023-02-12 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0019_rename_appointment_appointmentslot_appointments_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopHours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("monday", "Monday"),
                            ("tuesday", "Tuesday"),
                            ("wednesday", "Wednesday"),
                            ("thursday", "Thursday"),
                            ("friday", "Friday"),
                            ("sunday", "Sunday"),
                        ],
                        max_length=10,
                    ),
                ),
                ("from_time", models.TimeField()),
                ("to_time", models.TimeField()),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shops.shop"
                    ),
                ),
            ],
            options={
                "verbose_name": "Shop Availability",
                "verbose_name_plural": "Shop Availability",
            },
        ),
        migrations.AddConstraint(
            model_name="shophours",
            constraint=models.UniqueConstraint(
                fields=("shop", "day"), name="shop_day_unique_combination"
            ),
        ),
    ]
