# Generated by Django 4.1.2 on 2023-02-14 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0020_shop_shop_email_shop_shop_phone_number"),
        ("shops", "0020_shophours_shophours_shop_day_unique_combination"),
    ]

    operations = []
