# Generated by Django 4.1.2 on 2023-02-22 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0021_merge_20230214_1647"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shophours",
            options={"verbose_name": "Shop Hours", "verbose_name_plural": "Shop Hours"},
        ),
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("completed", "Completed"),
                    ("no show", "No Show"),
                    ("in_progress", "In Progress"),
                    ("done", "Done"),
                    ("rework", "Rework"),
                    ("pending", "Pending"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=12,
                verbose_name="status",
            ),
        ),
    ]
