# Generated by Django 4.1.2 on 2023-02-23 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0009_quote_created_at_quoterequest_created_at"),
        ("shops", "0022_alter_shophours_options_alter_appointment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="quote",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="quotes.quote",
            ),
        ),
    ]
