# Generated by Django 4.1.2 on 2023-02-23 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0023_appointment_quote"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workorder",
            name="grand_total",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="grand total amount",
            ),
        ),
    ]
