# Generated by Django 4.1.2 on 2023-02-23 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_employeedata_shop"),
        ("shops", "0024_alter_workorder_grand_total"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workorder",
            name="employee",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.employee",
            ),
        ),
    ]
