# Generated by Django 4.1.2 on 2023-02-25 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0004_alter_vehicle_year"),
        ("shops", "0025_alter_workorder_employee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="vehicle",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="vehicles.vehicle",
            ),
        ),
    ]
