# Generated by Django 4.1.2 on 2023-03-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0026_alter_appointment_vehicle"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorder",
            name="is_visible_to_customer",
            field=models.BooleanField(default=False),
        ),
    ]
