# Generated by Django 4.1.2 on 2023-03-06 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_employeedata_shop"),
        ("shops", "0027_workorder_is_visible_to_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shop",
            name="shop_owner",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.shopowner"
            ),
        ),
    ]
