# Generated by Django 4.1.2 on 2023-03-26 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0004_alter_vehicle_year"),
        ("shops", "0028_alter_shop_shop_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workorder",
            name="quote",
        ),
        migrations.AddField(
            model_name="appointment",
            name="service",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="shops.service",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="vehicle",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="vehicles.vehicle",
            ),
        ),
    ]
