# Generated by Django 4.1.2 on 2023-03-26 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0030_alter_appointment_quote_alter_appointment_service_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="appointment",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("quote__isnull", False), ("service__isnull", True)),
                    models.Q(("quote__isnull", True), ("service__isnull", False)),
                    _connector="OR",
                ),
                name="either_provide_quote_or_service_not_both",
            ),
        ),
    ]
