# Generated by Django 4.1.2 on 2023-01-19 20:58

from django.db import migrations, models
import django.db.models.deletion
import misc.models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0005_remove_quoterequest_images"),
        ("misc", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageQuote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "photo",
                    models.ImageField(
                        upload_to=misc.models.upload_to, verbose_name="Image"
                    ),
                ),
                (
                    "quote_request",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quotes.quoterequest",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Image",
        ),
    ]
