# Generated by Django 4.1.2 on 2023-01-19 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("misc", "0002_imagequote_delete_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="imagequote",
            name="quote_request",
        ),
    ]
