# Generated by Django 4.1.2 on 2023-01-29 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("misc", "0006_imagequote_quote_request"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="imagequote",
            name="title",
        ),
    ]
