# Generated by Django 4.1.2 on 2023-03-20 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("misc", "0007_remove_imagequote_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="imagequote",
            name="quote_request_batch_id",
            field=models.UUIDField(default=None, null=True),
        ),
    ]
