# Generated by Django 4.1.2 on 2023-03-20 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("misc", "0008_imagequote_quote_request_batch_id"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="imagequote",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("quote_request", None), ("quote_request__isnull", False)),
                    models.Q(
                        ("quote_request_batch_id", None),
                        ("quote_request_batch_id__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="Either provide a quote request or a quote request batch id",
            ),
        ),
    ]
