# Generated by Django 4.1.2 on 2023-03-26 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("misc", "0008_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="read",
            field=models.BooleanField(default=False),
        ),
    ]
