# Generated by Django 4.1.2 on 2023-03-26 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("misc", "0009_notification_read"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="link",
            field=models.CharField(blank=True, max_length=2000, verbose_name="link"),
        ),
    ]
