# Generated by Django 4.1.2 on 2023-03-27 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("misc", "0010_notification_link"),
        (
            "misc",
            "0010_remove_imagequote_either provide a quote request or a quote request batch id_and_more",
        ),
    ]

    operations = []
