# Generated by Django 4.1.2 on 2022-11-07 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(max_length=6, verbose_name="postal code"),
                ),
                ("street", models.CharField(max_length=255, verbose_name="street")),
                ("city", models.CharField(max_length=255, verbose_name="city")),
                ("country", models.CharField(max_length=255, verbose_name="country")),
                ("province", models.CharField(max_length=2, verbose_name="province")),
            ],
            options={
                "verbose_name": "Address",
                "verbose_name_plural": "Addresses",
            },
        ),
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "num_employees",
                    models.IntegerField(default=0, verbose_name="number of employees"),
                ),
                (
                    "num_bays",
                    models.IntegerField(
                        default=1, verbose_name="number of service bays"
                    ),
                ),
                (
                    "availability",
                    models.CharField(max_length=255, verbose_name="available hours"),
                ),
                (
                    "shopHours",
                    models.CharField(max_length=255, verbose_name="shop hours"),
                ),
                (
                    "address",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, to="shops.address"
                    ),
                ),
                (
                    "shop_owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.shopowner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shop",
                "verbose_name_plural": "Shops",
            },
        ),
    ]
