# Generated by Django 4.1.2 on 2022-11-07 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0003_rename_shophours_shop_shop_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="name",
            field=models.CharField(
                default="defaultShop", max_length=255, verbose_name="shop name"
            ),
            preserve_default=False,
        ),
    ]
