# Generated by Django 4.1.2 on 2022-11-08 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0005_alter_shop_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="province",
            field=models.CharField(max_length=10, verbose_name="province"),
        ),
    ]
