# Generated by Django 4.1.2 on 2022-11-08 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0006_alter_address_province"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shop",
            name="num_employees",
        ),
    ]
