# Generated by Django 4.1.2 on 2022-11-10 00:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0008_invitation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitation",
            name="invitation_key",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="UUID",
            ),
        ),
    ]
