# Generated by Django 4.1.2 on 2022-11-10 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0009_alter_invitation_invitation_key"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="invitation",
            unique_together={("shop", "email")},
        ),
    ]
