# Generated by Django 4.1.2 on 2022-11-10 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0007_remove_shop_num_employees"),
        ("accounts", "0003_employeedata_shop"),
        ("quotes", "0002_alter_quote_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="quoterequest",
            name="shop",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="shops.shop"
            ),
        ),
        migrations.AddField(
            model_name="quoterequest",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.customer",
            ),
        ),
    ]
