# Generated by Django 4.1.2 on 2022-11-09 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("shops", "0007_remove_shop_num_employees"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuoteRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preferred_date",
                    models.DateField(blank=True, verbose_name="preferred date"),
                ),
                (
                    "preferred_time",
                    models.TimeField(blank=True, verbose_name="preferred time"),
                ),
                (
                    "description",
                    models.CharField(max_length=1000, verbose_name="description"),
                ),
            ],
            options={
                "verbose_name": "Quote Request",
                "verbose_name_plural": "Quote Requests",
            },
        ),
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW_QUOTE", "New Quote"),
                            ("ACCEPTED", "Accepted"),
                            ("IN_PROGRESS", "In Progress"),
                            ("DONE", "Done"),
                            ("REWORK", "Rework"),
                        ],
                        default="NEW_QUOTE",
                        max_length=12,
                        verbose_name="status",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=19, verbose_name="price"
                    ),
                ),
                (
                    "estimated_time",
                    models.CharField(max_length=255, verbose_name="estimated time"),
                ),
                ("expiry_date", models.DateField(verbose_name="expiry date")),
                (
                    "quote_request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quotes.quoterequest",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shops.shop"
                    ),
                ),
            ],
            options={
                "verbose_name": "Quote",
                "verbose_name_plural": "Quotes",
            },
        ),
    ]
