# Generated by Django 4.1.2 on 2023-01-02 20:16

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("misc", "0001_initial"),
        ("quotes", "0003_quoterequest_shop_quoterequest_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quoterequest",
            name="preferred_date",
        ),
        migrations.RemoveField(
            model_name="quoterequest",
            name="preferred_time",
        ),
        migrations.AddField(
            model_name="quoterequest",
            name="images",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="misc.image"
            ),
        ),
        migrations.AddField(
            model_name="quoterequest",
            name="preferred_email",
            field=models.EmailField(
                blank=True, max_length=255, null=True, verbose_name="email address"
            ),
        ),
        migrations.AddField(
            model_name="quoterequest",
            name="preferred_phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, region=None
            ),
        ),
    ]
