# Generated by Django 4.1.2 on 2023-01-19 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0004_remove_quoterequest_preferred_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quoterequest",
            name="images",
        ),
    ]
