# Generated by Django 4.1.2 on 2023-01-23 23:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0005_remove_quoterequest_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="quoterequest",
            name="preferred_date",
            field=models.DateField(
                blank=True,
                default=django.utils.timezone.now,
                verbose_name="preferred date",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="quoterequest",
            name="preferred_time",
            field=models.TimeField(
                blank=True,
                default=django.utils.timezone.now,
                verbose_name="preferred time",
            ),
            preserve_default=False,
        ),
    ]
