# Generated by Django 4.1.2 on 2023-01-29 22:05

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0005_remove_quoterequest_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="quoterequest",
            name="preferred_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="preferred date"
            ),
        ),
        migrations.AddField(
            model_name="quoterequest",
            name="preferred_time",
            field=models.TimeField(
                blank=True, null=True, verbose_name="preferred time"
            ),
        ),
        migrations.AlterField(
            model_name="quoterequest",
            name="preferred_phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region=None
            ),
        ),
    ]
