# Generated by Django 4.1.2 on 2023-02-24 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0009_quote_created_at_quoterequest_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="notes",
            field=models.CharField(blank=True, max_length=2000, verbose_name="notes"),
        ),
    ]
