# Generated by Django 4.1.2 on 2023-03-01 21:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0010_quote_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="quoterequest",
            name="batch_id",
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name="quoterequest",
            name="preferred_part_condition",
            field=models.CharField(
                blank=True,
                choices=[("new", "New"), ("used", "Used")],
                max_length=4,
                null=True,
                verbose_name="Condition",
            ),
        ),
        migrations.AddField(
            model_name="quoterequest",
            name="preferred_part_type",
            field=models.CharField(
                blank=True,
                choices=[("oem", "OEM"), ("aftermarket", "Aftermarket")],
                max_length=11,
                null=True,
                verbose_name="Type",
            ),
        ),
    ]
