# Generated by Django 4.1.2 on 2023-03-17 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0011_quotecomment"),
        ("quotes", "0011_quoterequest_batch_id_and_more"),
    ]

    operations = []
