# Generated by Django 4.1.2 on 2022-11-07 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0001_initial"),
        ("accounts", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeedata",
            name="shop",
            field=models.ForeignKey(
                default=-1,
                on_delete=django.db.models.deletion.CASCADE,
                to="shops.shop",
            ),
            preserve_default=False,
        ),
    ]
